// Code generated by MockGen. DO NOT EDIT.
// Source: tezos-delegation/internal/db (interfaces: DelegationRepositoryInterface)

package mocks

import (
	context "context"
	reflect "reflect"
	model "tezos-delegation/internal/model"

	gomock "github.com/golang/mock/gomock"
)

type MockDelegationRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDelegationRepositoryInterfaceMockRecorder
}

type MockDelegationRepositoryInterfaceMockRecorder struct {
	mock *MockDelegationRepositoryInterface
}

func NewMockDelegationRepositoryInterface(ctrl *gomock.Controller) *MockDelegationRepositoryInterface {
	mock := &MockDelegationRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockDelegationRepositoryInterfaceMockRecorder{mock}
	return mock
}

func (m *MockDelegationRepositoryInterface) EXPECT() *MockDelegationRepositoryInterfaceMockRecorder {
	return m.recorder
}

func (m *MockDelegationRepositoryInterface) InsertDelegations(arg0 []*model.Delegation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertDelegations", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockDelegationRepositoryInterfaceMockRecorder) InsertDelegations(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertDelegations", reflect.TypeOf((*MockDelegationRepositoryInterface)(nil).InsertDelegations), arg0)
}

func (m *MockDelegationRepositoryInterface) GetLatestTzktID(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestTzktID", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockDelegationRepositoryInterfaceMockRecorder) GetLatestTzktID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestTzktID", reflect.TypeOf((*MockDelegationRepositoryInterface)(nil).GetLatestTzktID), arg0)
}

func (m *MockDelegationRepositoryInterface) ListDelegations(arg0 context.Context, arg1, arg2 int, arg3 *int) ([]model.Delegation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDelegations", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]model.Delegation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockDelegationRepositoryInterfaceMockRecorder) ListDelegations(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDelegations", reflect.TypeOf((*MockDelegationRepositoryInterface)(nil).ListDelegations), arg0, arg1, arg2, arg3)
}
