version: '3.8'

services:
  db:
    image: postgres:16
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    restart: unless-stopped
    networks:
      - internal_net

  service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - internal_net

volumes:
  postgres_data: 
networks:
  internal_net:
    driver: bridge 