version: '3.8'

services:
  xtz-postgres:
    container_name: "xtz-postgres"
    image: postgres:16
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - xtz_data:/var/lib/postgresql/data
      - ./data/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    restart: unless-stopped
    networks:
      - internal_net

  xtz-service:
    container_name: "xtz-service"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    depends_on:
      - xtz-postgres
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - internal_net

volumes:
  xtz_data: 
networks:
  internal_net:
    driver: bridge 